apiVersion: v1
kind: Service
metadata:
  name: sofid__CI_BUILD_REF_SLUG__
  namespace: sofid
  labels:
    app: sofid__CI_BUILD_REF_SLUG__
#  annotations:
#    prometheus.io/scrape: "true"
#    prometheus.io/port: "$PORT"
#    prometheus.io/scheme: "http"
#    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  ports:
    - name: $MICROSERVICE
      port: $PORT
#      targetPort: $MICROSERVICE
#      protocol: TCP
      nodePort: 30000
  selector:
    app: sofid__CI_BUILD_REF_SLUG__